<?php
require_once dirname(dirname(dirname(dirname(__DIR__)))) . '/config/koneksi.php';
$conn = $mysqli;
$filter_month = isset($_POST['month']) ? (int) $_POST['month'] : (int) date('n');
$filter_year = isset($_POST['year']) ? (int) $_POST['year'] : (int) date('Y');
if ($filter_month < 1 || $filter_month > 12) $filter_month = (int) date('n');
if ($filter_year < 2020 || $filter_year > ((int) date('Y') + 1)) $filter_year = (int) date('Y');
$start_date = sprintf('%04d-%02d-01', $filter_year, $filter_month);
$end_date = date('Y-m-t', strtotime($start_date));
$days_in_month = (int) date('t', strtotime($start_date));
$month_labels = [1=>'Januari',2=>'Februari',3=>'Maret',4=>'April',5=>'Mei',6=>'Juni',7=>'Juli',8=>'Agustus',9=>'September',10=>'Oktober',11=>'November',12=>'Desember'];
$sql = "SELECT ki.tgl_masuk,rp.no_rawat,p.nm_pasien,p.jk,CONCAT(IFNULL(k.kd_kamar,'-'),' / ',IFNULL(b.nm_bangsal,'-')) AS kamar,IFNULL(ki.lama,0) AS lama_dirawat,IFNULL(ki.stts_pulang,'-') AS status_pulang,CASE WHEN rp.kd_pj='A09' THEN 'Umum' WHEN rp.kd_pj='BPJ' THEN 'BPJS' WHEN rp.kd_pj='A92' THEN 'Asuransi' ELSE IFNULL(pj.png_jawab,'-') END AS jenis_pembayaran,COALESCE(bill.total_tagihan,ki.ttl_biaya,0) AS total_biaya FROM kamar_inap ki INNER JOIN reg_periksa rp ON ki.no_rawat=rp.no_rawat INNER JOIN pasien p ON rp.no_rkm_medis=p.no_rkm_medis LEFT JOIN kamar k ON ki.kd_kamar=k.kd_kamar LEFT JOIN bangsal b ON k.kd_bangsal=b.kd_bangsal LEFT JOIN penjab pj ON rp.kd_pj=pj.kd_pj LEFT JOIN (SELECT no_rawat,MAX(totalbiaya) AS total_tagihan FROM billing WHERE status='Tagihan' GROUP BY no_rawat) bill ON bill.no_rawat=rp.no_rawat WHERE ki.tgl_masuk BETWEEN ? AND ? AND rp.status_lanjut='Ranap' AND (ki.stts_pulang IS NULL OR ki.stts_pulang<>'Pindah Kamar') ORDER BY ki.tgl_masuk ASC,rp.no_rawat ASC";
$stmt = $conn->prepare($sql); if (!$stmt) die('Query prepare gagal: '.$conn->error); $stmt->bind_param('ss',$start_date,$end_date); $stmt->execute(); $result = $stmt->get_result();
$data_rows=[]; $total_biaya_keseluruhan=0; $total_lama_dirawat=0; $pasien_harian=[]; $biaya_harian=[]; $jenis_bayar_summary=['Umum'=>0,'BPJS'=>0,'Asuransi'=>0,'Lainnya'=>0];
for ($day=1;$day<=$days_in_month;$day++) { $key=sprintf('%04d-%02d-%02d',$filter_year,$filter_month,$day); $pasien_harian[$key]=0; $biaya_harian[$key]=0; }
while ($row=$result->fetch_assoc()) { $data_rows[]=$row; $total_biaya_keseluruhan+=(float)$row['total_biaya']; $total_lama_dirawat+=(float)$row['lama_dirawat']; if(isset($pasien_harian[$row['tgl_masuk']])){$pasien_harian[$row['tgl_masuk']]++; $biaya_harian[$row['tgl_masuk']]+=(float)$row['total_biaya'];} if(isset($jenis_bayar_summary[$row['jenis_pembayaran']])){$jenis_bayar_summary[$row['jenis_pembayaran']]++;}else{$jenis_bayar_summary['Lainnya']++;} }
$stmt->close(); $total_pasien=count($data_rows); $rata_lama_dirawat=$total_pasien>0?$total_lama_dirawat/$total_pasien:0; $hari_terpadat_tanggal='-'; $hari_terpadat_jumlah=0; foreach($pasien_harian as $tgl=>$jml){ if($jml>$hari_terpadat_jumlah){$hari_terpadat_jumlah=$jml;$hari_terpadat_tanggal=$tgl;}}
$chart_labels=[]; $chart_pasien=[]; $chart_biaya=[]; foreach($pasien_harian as $tgl=>$jml){$chart_labels[]=date('d M',strtotime($tgl));$chart_pasien[]=$jml;$chart_biaya[]=round($biaya_harian[$tgl]);}
$payment_labels=[]; $payment_values=[]; foreach($jenis_bayar_summary as $label=>$value){ if($value>0){$payment_labels[]=$label;$payment_values[]=$value;}}
?>
<br>
<style>
.ranap-wrap{display:grid;gap:18px}.ranap-hero,.ranap-panel,.ranap-card{background:#fff;border:1px solid rgba(108,151,219,.16);box-shadow:0 18px 36px rgba(74,101,145,.10);border-radius:22px}.ranap-hero{padding:24px;background:linear-gradient(135deg,#f7fbff,#deecff 58%,#fff6ea)}.ranap-title{margin:0 0 8px;font-size:34px;font-weight:800;color:#21406c}.ranap-sub{margin:0;color:#587192;font-size:14px;max-width:760px}.ranap-filter{display:flex;flex-wrap:wrap;gap:10px;align-items:end;margin-top:18px}.ranap-filter .form-control,.ranap-filter .btn{border-radius:12px}.ranap-filter .btn-primary{background:linear-gradient(135deg,#3487e3,#1f5fae);border:none}.ranap-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}.ranap-card{padding:18px}.ranap-card:nth-child(1){background:linear-gradient(135deg,#edf6ff,#fff)}.ranap-card:nth-child(2){background:linear-gradient(135deg,#eefcf5,#fff)}.ranap-card:nth-child(3){background:linear-gradient(135deg,#fff5ec,#fff)}.ranap-card:nth-child(4){background:linear-gradient(135deg,#f5f1ff,#fff)}.ranap-k{font-size:12px;letter-spacing:1px;text-transform:uppercase;color:#6c84a8}.ranap-v{font-size:28px;font-weight:800;color:#1f3f6d;line-height:1.1;margin-top:8px}.ranap-s{margin-top:8px;font-size:12px;color:#60789d}.ranap-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px}.ranap-panel{padding:20px}.ranap-head{display:flex;justify-content:space-between;gap:12px;align-items:start;margin-bottom:14px}.ranap-h{margin:0;font-size:20px;font-weight:800;color:#1e3d6a}.ranap-d{margin:4px 0 0;color:#6f84a4;font-size:13px}.ranap-pill{display:inline-flex;padding:8px 12px;border-radius:999px;background:#eef5ff;color:#3468b0;font-size:12px;font-weight:700}.ranap-chart{position:relative;min-height:320px}@media(max-width:991px){.ranap-grid{grid-template-columns:1fr}}@media(max-width:576px){.ranap-title{font-size:28px}.ranap-filter{flex-direction:column;align-items:stretch}}
</style>
<div class="ranap-wrap">
<section class="ranap-hero"><h1 class="ranap-title">Rawat Inap Harian</h1><p class="ranap-sub">Pantau arus pasien, total biaya, dan komposisi pembayaran rawat inap dalam satu tampilan yang lebih cepat dibaca.</p><form method="post" class="ranap-filter"><div class="form-group mb-0"><label for="month"><strong>Bulan</strong></label><select name="month" id="month" class="form-control form-control-sm"><?php foreach($month_labels as $n=>$name): ?><option value="<?php echo $n; ?>" <?php echo ($filter_month===$n)?'selected':''; ?>><?php echo htmlspecialchars($name,ENT_QUOTES,'UTF-8'); ?></option><?php endforeach; ?></select></div><div class="form-group mb-0"><label for="year"><strong>Tahun</strong></label><select name="year" id="year" class="form-control form-control-sm"><?php for($year=2020;$year<=((int)date('Y')+1);$year++): ?><option value="<?php echo $year; ?>" <?php echo ($filter_year===$year)?'selected':''; ?>><?php echo $year; ?></option><?php endfor; ?></select></div><button type="submit" class="btn btn-primary btn-sm px-4">Tampilkan Data</button></form></section>
<section class="ranap-cards"><div class="ranap-card"><div class="ranap-k">Total Pasien</div><div class="ranap-v"><?php echo number_format($total_pasien,0,',','.'); ?></div><div class="ranap-s"><?php echo htmlspecialchars($month_labels[$filter_month],ENT_QUOTES,'UTF-8').' '.$filter_year; ?></div></div><div class="ranap-card"><div class="ranap-k">Total Biaya</div><div class="ranap-v"><?php echo number_format($total_biaya_keseluruhan,0,',','.'); ?></div><div class="ranap-s">Sumber utama dari billing tagihan</div></div><div class="ranap-card"><div class="ranap-k">Rata Lama Dirawat</div><div class="ranap-v"><?php echo number_format($rata_lama_dirawat,1,',','.'); ?> hari</div><div class="ranap-s">Rerata seluruh pasien pada tabel</div></div><div class="ranap-card"><div class="ranap-k">Hari Terpadat</div><div class="ranap-v"><?php echo $hari_terpadat_jumlah>0?number_format($hari_terpadat_jumlah,0,',','.').' px':'-'; ?></div><div class="ranap-s"><?php echo $hari_terpadat_tanggal!=='-'?htmlspecialchars(date('d M Y',strtotime($hari_terpadat_tanggal)),ENT_QUOTES,'UTF-8'):'Belum ada data'; ?></div></div></section>
<section class="ranap-grid"><div class="ranap-panel"><div class="ranap-head"><div><h2 class="ranap-h">Tren Pasien dan Biaya Harian</h2><p class="ranap-d">Batang menunjukkan jumlah pasien, garis menunjukkan total biaya per hari.</p></div><span class="ranap-pill"><?php echo htmlspecialchars($start_date,ENT_QUOTES,'UTF-8'); ?> s.d. <?php echo htmlspecialchars($end_date,ENT_QUOTES,'UTF-8'); ?></span></div><div class="ranap-chart"><canvas id="chartRanapHarian"></canvas></div></div><div class="ranap-panel"><div class="ranap-head"><div><h2 class="ranap-h">Komposisi Pembayaran</h2><p class="ranap-d">Distribusi jenis pembayaran pasien rawat inap pada periode ini.</p></div></div><div class="ranap-chart"><canvas id="chartPembayaranRanap"></canvas></div></div></section>
<section class="ranap-panel"><div class="ranap-head"><div><h2 class="ranap-h">Detail Pasien Rawat Inap</h2><p class="ranap-d">Periode data: <strong><?php echo htmlspecialchars($month_labels[$filter_month],ENT_QUOTES,'UTF-8'); ?> <?php echo (int)$filter_year; ?></strong> (<?php echo htmlspecialchars($start_date,ENT_QUOTES,'UTF-8'); ?> s.d. <?php echo htmlspecialchars($end_date,ENT_QUOTES,'UTF-8'); ?>)</p></div></div><div class="table-responsive-sm"><table class="table table-sm table-bordered table-hover" id="table4" style="width:100%;margin-top:10px;font-size:12px;"><thead class="thead-dark"><tr><th style="text-align:center;">No.</th><th>Tanggal Masuk</th><th>No Rawat</th><th>Nama Pasien</th><th>Jenis Kelamin</th><th>Kamar</th><th>Lama Dirawat</th><th>Status Pulang</th><th>Jenis Pembayaran</th><th>Total Biaya</th></tr></thead><tbody><?php if(empty($data_rows)): ?><tr><td colspan="10" style="text-align:center;">Tidak ada data rawat inap pada periode ini.</td></tr><?php else: ?><?php $no=1; foreach($data_rows as $row): ?><tr><td style="text-align:center;"><?php echo $no++; ?></td><td><?php echo htmlspecialchars($row['tgl_masuk'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($row['no_rawat'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($row['nm_pasien'],ENT_QUOTES,'UTF-8'); ?></td><td style="text-align:center;"><?php echo htmlspecialchars($row['jk'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($row['kamar'],ENT_QUOTES,'UTF-8'); ?></td><td style="text-align:center;"><?php echo (int)$row['lama_dirawat']; ?></td><td><?php echo htmlspecialchars($row['status_pulang'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo htmlspecialchars($row['jenis_pembayaran'],ENT_QUOTES,'UTF-8'); ?></td><td style="text-align:right;"><?php echo number_format((float)$row['total_biaya'],0,',','.'); ?></td></tr><?php endforeach; endif; ?></tbody><?php if(!empty($data_rows)): ?><tfoot><tr style="background-color:#f8f9fa;font-weight:bold;"><td colspan="9" style="text-align:right;">Total Biaya Keseluruhan</td><td style="text-align:right;"><?php echo number_format($total_biaya_keseluruhan,0,',','.'); ?></td></tr></tfoot><?php endif; ?></table></div></section>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>(function(){const l=<?php echo json_encode($chart_labels); ?>,p=<?php echo json_encode($chart_pasien); ?>,b=<?php echo json_encode($chart_biaya); ?>,pl=<?php echo json_encode($payment_labels); ?>,pv=<?php echo json_encode($payment_values); ?>,nf=new Intl.NumberFormat('id-ID');const c=document.getElementById('chartRanapHarian');if(c){const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,320);g.addColorStop(0,'rgba(46,134,222,.88)');g.addColorStop(1,'rgba(46,134,222,.18)');new Chart(x,{type:'bar',data:{labels:l,datasets:[{type:'bar',label:'Jumlah Pasien',data:p,backgroundColor:g,borderRadius:10,borderSkipped:false,yAxisID:'y',maxBarThickness:22},{type:'line',label:'Total Biaya',data:b,borderColor:'#ff9800',pointBackgroundColor:'#ff9800',pointBorderColor:'#fff',pointRadius:4,borderWidth:3,tension:.35,fill:false,yAxisID:'y1'}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:10,color:'#496280'}},tooltip:{callbacks:{label:function(ctx){return ctx.dataset.label==='Total Biaya'?ctx.dataset.label+': Rp '+nf.format(ctx.raw||0):ctx.dataset.label+': '+nf.format(ctx.raw||0);}}}},scales:{x:{grid:{display:false},ticks:{color:'#6f84a4',maxRotation:0,autoSkip:true,maxTicksLimit:10}},y:{beginAtZero:true,ticks:{color:'#4d6c95'},grid:{color:'rgba(113,138,180,.12)'}},y1:{beginAtZero:true,position:'right',grid:{drawOnChartArea:false},ticks:{color:'#dd7d00',callback:function(v){return 'Rp '+nf.format(v);}}}}}});}const d=document.getElementById('chartPembayaranRanap');if(d){new Chart(d,{type:'doughnut',data:{labels:pl.length?pl:['Belum Ada Data'],datasets:[{data:pv.length?pv:[1],backgroundColor:pv.length?['#2e86de','#27ae60','#ff9f43','#8e44ad']:['#dbe7f7'],borderWidth:0,hoverOffset:8}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:10,color:'#496280'}},tooltip:{callbacks:{label:function(ctx){return ctx.label+': '+nf.format(ctx.raw||0)+' pasien';}}}}}});}})();</script>